### ISSUE TITLE
More robust reading of lidar files

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/Utilities#4]
- Create a more modular way to read in 3dd data, or rxp data, or txt data

- improve the way scannum is calculated so it's more robust

**Comment by KateBrodie** [comment]
@hokiespurs @atdyer @njspore 
This might have higher priority given the fact we're using the z210 during the experiment as well. at the very least we need something to read .3dd files.

**Comment by hokiespurs** [comment]
@atdyer add concerns here for how to fix readrxp and getrxp in the future. portability vs typability battle: commence.

Also to think about. We'll have two exes, one to read 3dd, one to read rxp. So function will need to handle that. 

@Kbrodie

**Comment by hokiespurs** [comment]
I have an idea that I think will work well at satisfy both our concerns. I Was thinking of putting a utilities/lidar/exe folder in the utilities repo, With RXPconvertLinux.exe and RXPconvertWindows.exe. We'll also add 3ddconvert windows and Linux exes in there eventually. Then our "readlidar" Matlab function will just try to call one of them (windows/Linux) with no parameters and check for functionality, it it fails, it will run the other one. It will also handle if it's a 3dd file or if it's an rxp file. Eventually the exe should be able to handle both types, but for now this oughta work. 

Yes, it's bad to put exes in a github repo, but I think this exe isn't really an "in-development" exe. Eventually it'd be nice to tristanify and combine 3ddConvert and RXPConvert, but we'll just copy new exes into the utilities GitHub and make another release when we do that.  

Thoughts?
@atdyer @katebrodie

**Comment by atdyer** [comment]
@hokiespurs @KateBrodie 

So the RXPconvert code is [already tristanified](https://github.com/FRF-Remote-Sensing/RXPconvert) and I've already got everything compiled and installed on the processing machine (minus the 3ddconvert code, which I plan on finishing up next week while I'm at the pier).

I really don't like the idea of putting executables up here because there's no guarantee that it will work on every machine (as we've seen with the 390 collect code). It's really easy and much more portable to just pull the code from github and compile on whatever machine you're using, and then point the matlab code to the executable. That's how all of the framescan processing is done -- see the [generate param file script](https://github.com/FRF-Remote-Sensing/DuneLidar/blob/dev/Setup/params/generateParamsFile.m), where you give it the path to the executables (or just leave them out completely if you've added the executable to your path). 

The matlab script should be able to tell the file type by looking at the extension, and then just call the appropriate executable.

**Comment by hokiespurs** [comment]
@atdyer @katebrodie

Nice hot link on the already tristanified! And awesome about the 3dd
shenanigans code!

I think 3dd code failed a bunch in windows because it was relying on a text
file that wasn't existing, rather than a compatibility issue.

So how do we cleanly handle everyone having a different path on their
computer? We call readrxp a few places in the code. Do we need to create a
global variable at the beginning of processing for the RXPConvert.exe
location? Or pass it as an argument all the way through the code.

Also, your average user won't know how to compile the cpp code on their
computer. So if we share our readrxp code with someone they might get
stuck. I think we should have a few potential exes on there they can try
first. I know the windows one has been relatively stable across most
platforms.

**Comment by KateBrodie** [comment]
@atdyer @hokiespurs

I = average user 😢

I think Nick recently had some issues with the 390 code on different
windows platforms? I could be wrong. I also know he was missing the
scannermod.dlls which helped when I gave that to him...maybe? I didnt keep
up with what you guys did to fix it.

**Comment by hokiespurs** [comment]
@atdyer @KateBrodie, thoughts

It'd be good to have this resolved before we go live

I think we should combine getRXPdata and the current readRXP.  The way it is written now is clearly not working.  I'm going to have to fix coregistration code becuase we don't have it written so you can pass in "first" or "last" or "all"

So here's a **salt life** stab at inputs and outputs.  
### INPUTS:
mandatory
- filename (as a string or as a structure)

optional
- type of returns (default = all)
- type of data to return (default = x,y,z,i,tint)
  - varargin for x,y,z,i,tint,tgps(coded with the intepolate fix and filenametime fix),scannum...etc 
    - if tgps is chosen, return data as tgps, but also return an integer for number of bad points
    - scannum is calculated, not directly from scanner
- exe to use ('default is that its on system path)
- rotation matrix (default = eye(1))

### OUTPUTS:
varargout based on what was passed in for type of data to return

**Comment by atdyer** [comment]
@hokiespurs 

I agree, there's been quite a few random bugs/needed functionality that keep popping up around these two functions. I'm going to code up a new version today that uses [InputParser](http://www.mathworks.com/help/matlab/matlab_prog/parse-function-inputs.html) so we'll have the flexibility to add new stuff in the future without screwing up what's already been coded.

**Comment by hokiespurs** [comment]
@atdyer you da real MVP

**Comment by atdyer** [comment]
@hokiespurs 

Work in progress [here](https://github.com/FRF-Remote-Sensing/Utilities/blob/master/Lidar/readRXPnew.m)

Got most of the basic stuff finished, I'll add the gps and scan number stuff after lunch. Start looking through it and let me know what you think.

**Comment by hokiespurs** [comment]
@KateBrodie 
per discussion with @atdyer 

1. Make modular so it can read 3dd or RXP files
2. Additional options for time
  - tgps (default)
    - This will do anything to fill with good gps data, use tgps from scanner, if theres some nans interpolate, if theres all nans use filename+tint
  - tint
    - lidar internal time
  - tfilename
    - filetime generated using tinternal and filename
  - tinterp
    - uses tgps from the scanner, if theres some nans, interpolate, if all nans, return nans
  - tgpsraw
    - uses tgps from scanner and doesnt try to fix nans
3. Add optional output for tgpsinfo, numNanInGPS, MaskOfNanInGPS, etc
  - So sometimes we'll want to know how tgps was generated. was it directly from the scanner? was in interpolated? was it from filename? How many gps points from the scanner were nan? Which gps points from the scanner were nans?

**Comment by atdyer** [comment]
@hokiespurs Please take a look at [readLidar](https://github.com/FRF-Remote-Sensing/Utilities/blob/master/Lidar/readLidar.m). Specifically, start on line 244 and make sure GPS time/internal time are being loaded the way they should. I fairly confident in the logic, but haven't tested every case.

varargout still a work in progress, will try to get to it this afternoon after everything else is up and running.

**Comment by hokiespurs** [comment]
@atdyer fixed this with a new readLidar script 609aae4

:+1: :+1:
