### ISSUE TITLE
readRXP function inputs - last vs allpoints?

### ISSUE THREAD

**Issue by KateBrodie** [FRF-Remote-Sensing/Utilities#6]
@atdyer @hokiespurs 

@njspore  and I are confused by inputs to readRXP. @njspore  noted that for coregistration and make baseline we need to return allpoints not just last in order to see some of our targets. However, it seems like to me that readRXP is hard-coded for 'last'?  I was going to change it to be an input but then i wondered if the varargin call already handled that...or maybe i need to add another if statement? What's the best way to handle this?

**Comment by hokiespurs** [comment]
@atdyer fixed this with a new readLidar script 609aae4

:+1:
